### ISSUE TITLE
Add a /changes endpoint to the object API

### ISSUE THREAD

**Issue by enridaga** [spice-h2020/linked-data-hub#12]
To query the activity log for a specific dataset and return the list of documents updated since day/time, sortable by time. The query should skip duplicated entries and only return the most recent update of a document.

**Comment by JaseMK** [comment]
Notes for implementation:
- https://<api_url>/changes/<dataset_id>
- Default limit to most recent xx entries (100?)
- Sort by datetime descending
- Add URL parameters:
    - since (datetime - agree on a format for this)
    - sort (0/1 - to reverse sort order)
    - limit (number of entries)

Do we need to return the entire AL entry? May need to remove certain attributes such as 'key' for security reasons? Or, only show changes that that were made using the user's key?

**Comment by enridaga** [comment]
> Do we need to return the entire AL entry? May need to remove certain attributes such as 'key' for security reasons? 

+1

> Or, only show changes that that were made using the user's key?
This maybe is not a good idea as malicious users could use this feature to test & find working keys?

However, it could be useful to know changes performed by keys belonging to certain users, but we can keep this as future work and makes sense only to help dataset managers to inspect the dataset history (as a LDH front-end feature)

**Comment by JaseMK** [comment]
/changes/ endpoint implemented in mkdf/api-factory v0.9.3
https://github.com/mkdf/api-factory/releases/tag/v0.9.3
