### ISSUE TITLE
How many documents are retrieved with /object/{dataset} API?

### ISSUE THREAD

**Issue by luigi-asprino** [spice-h2020/linked-data-hub#13]
It seems that the API returns a fixed number of documents (100). Is there any way to tell the API to return all the documents in the dataset?

**Comment by enridaga** [comment]
The /object endpoint has limited functionalities, mainly targeted to lookup of known documents. For listing content, better use the /browse endpoint that has more flexibility, including pagination.

**Comment by luigi-asprino** [comment]
Ok thanks
