### ISSUE TITLE
Error when creating stream datasets

### ISSUE THREAD

**Issue by JaseMK** [spice-h2020/linked-data-hub#15]
Unexpected HTTP code: 400

URL: https://api2.mksmart.org/management/datasets

{"error":"Bad request, missing dataset id or access key"}

**Comment by enridaga** [comment]
Is this being resolved?

**Comment by JaseMK** [comment]
Fixed in "7339d87bb7ceee966d951061d59b5ee71304b4f5" (v0.9.3) on mkdf/mkdf-stream
