### ISSUE TITLE
JSON data browser

### ISSUE THREAD

**Issue by enridaga** [spice-h2020/linked-data-hub#22]
It would be nice if we could browse the content of the JSON document store, and allow to edit the JSON documents from the LDH UI, create new documents, delete documents.

**Comment by JaseMK** [comment]
Development in progress on dev/JSONBrowser branch of mkdf/mkdf-stream
https://github.com/mkdf/mkdf-stream/tree/dev/JSONBrowser

**Comment by JaseMK** [comment]
Dev branched pulled into master.
Browse functionality implemented in mkdf/mkdf-strram v0.11.2
https://github.com/mkdf/mkdf-stream/releases/tag/v0.11.2 

Now working on JSON create/update/delete...

**Comment by JaseMK** [comment]
JSON create/update/delete now implemented in mkdf/mkdf-stream v0.11.3
https://github.com/mkdf/mkdf-stream/releases/tag/v0.11.3
