### ISSUE TITLE
Activate SPARQL mirroring on-demand

### ISSUE THREAD

**Issue by enridaga** [spice-h2020/linked-data-hub#23]
The RDF mirror of the JSON documents is being kept in sync by the RDF Uploader.  However, sometimes we need to refresh the transformations, on demand. This may be a feature of the LDH administrator only and could target (a) specific documents or (b) an entire dataset.

**Comment by JaseMK** [comment]
Implemented as of mkdf/mkdf-sparql v0.10.0
https://github.com/mkdf/mkdf-sparql/releases/tag/v0.10.0
