### ISSUE TITLE
Request access

### ISSUE THREAD

**Issue by enridaga** [spice-h2020/linked-data-hub#30]
Provide a workflow for requesting permissions to the administrator of a dataset.

https://github.com/spice-h2020/linked-data-layer-requirements/issues/7

**Comment by JaseMK** [comment]
In development on mkdf/mkdf-datasets, dev/request/access branch
https://github.com/mkdf/mkdf-datasets/tree/dev/request-access

**Comment by JaseMK** [comment]
Complete, in mkdf/mkdf-datasets v0.11.1
https://github.com/mkdf/mkdf-datasets/releases/tag/v0.11.1

Also contains updates to
mkdf-mkdf-stream (v0.11.7)
https://github.com/mkdf/mkdf-stream/releases/tag/v0.11.7

mkdf/mkdf-core (v0.9.7)
https://github.com/mkdf/mkdf-core/releases/tag/v0.9.7
